
INSERT INTO TIPO_CAMBIO (COD_MONEDA, DES_MONEDA, VAL_TIPO_CAMBIO) values ('PEN','SOL',1.00);
INSERT INTO TIPO_CAMBIO (COD_MONEDA, DES_MONEDA, VAL_TIPO_CAMBIO) values ('USD','DÓLAR',3.7289);
INSERT INTO TIPO_CAMBIO (COD_MONEDA, DES_MONEDA, VAL_TIPO_CAMBIO) values ('EUR','EURO',3.9136);